name: tojjar_delivery_app
description: A new Flutter project.

publish_to: null
version: 1.0.2+9

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.1.0
  easy_localization: null
  file_picker: ^5.3.2
  firebase_core: ^2.11.0
  firebase_dynamic_links: ^5.2.0
  firebase_messaging: ^14.6.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^14.1.1
  flutter_polyline_points: ^1.0.0
  flutter_screenutil: ^5.7.0
  flutter_svg: null
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.6
  http: ^0.13.3
  image_picker: ^0.8.9
  loading_animation_widget: ^1.2.0+3
  path_provider: ^2.0.15
  pdf: ^3.10.4
  permission_handler: ^10.3.0
  pin_code_fields: ^7.4.0
  printing: ^5.11.0
  shared_preferences: ^2.1.1
  signature: any
  swipe_to: ^1.0.2
  url_launcher: ^6.1.11
  custom_info_window: ^1.0.1
  cupertino_back_gesture: ^0.1.0
  
 


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Images/Tojjar-delivery-app-logo.jpg"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translation/
    - assets/images/
    - assets/fonts/
